/**
 * memoryStore — per-(user, scenario) gameplay memory for fired mode.
 *
 * v0.8.2. Goal: when a returning player picks the same scenario, the HR
 * character should "remember" what tactics worked last time and pre-empt
 * them. Mechanically:
 *
 *   1. After each round ends, the client POSTs the messages + outcome to
 *      /api/fired/memory/record. Server LLM-summarizes the player's main
 *      tactic in 1-2 sentences and appends a `PlayMemory` record.
 *   2. On the next /chat call for the same scenarioId, the route reads
 *      the memory list and injects it into the HR system prompt:
 *      "这位员工之前来过 N 次,用过这些招数:[…]; 请预判,不要重蹈覆辙".
 *   3. The FiredLanding card surfaces a "你打过 N 次" badge so the user
 *      knows their history is being tracked.
 *
 * Storage shape on disk (packages/server/data/user_memory.json):
 *
 *   {
 *     "<userId>": {
 *       "<scenarioId>": [
 *         { ts, outcome, tactic, tookRounds, finalRatio },
 *         …last 5 only, oldest dropped on overflow
 *       ]
 *     }
 *   }
 *
 * NOT a security identity — userId is the same pseudonymous localStorage
 * id we use everywhere else (X-User-Id header, see utils/userId.ts on the
 * client). Spoofable, by design — the worst case is "I see someone else's
 * scenario history" which is fine because that history is just summary
 * strings of public chat sessions.
 *
 * Capped at 5 entries per (user, scenario) to keep prompt budget bounded.
 * If we ever want longer history we can add a "summary of summaries"
 * compaction pass — for now 5 is plenty (it's the equivalent of "you've
 * already played this scenario 5 times this week").
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const DATA_DIR  = path.resolve(__dirname, '..', '..', 'data');
const DATA_FILE = path.join(DATA_DIR, 'user_memory.json');

const MAX_MEMORIES_PER_SCENARIO = 5;

export interface PlayMemory {
  /** Unix ms when the round ended. */
  ts: number;
  /** Win/lose label as set by the round-end LLM scorer. */
  outcome: 'win' | 'partial' | 'lose';
  /** 1-2 sentence summary of the player's main tactic, generated by the
   *  tactic summarizer. Goes verbatim into the HR system prompt. */
  tactic: string;
  /** How many user-message rounds it took to reach the outcome. Helpful
   *  for the UI to surface "你 7 轮就赢了" type messages. */
  tookRounds: number;
  /** Compensation actually achieved / max possible — 0 to 1. Drives the
   *  "your best result" stat in the FiredLanding badge. */
  finalRatio: number;
}

interface StoreShape {
  /** userId → scenarioId → PlayMemory[] (newest last) */
  byUser: Record<string, Record<string, PlayMemory[]>>;
}

let cache: StoreShape | null = null;
let loadPromise: Promise<StoreShape> | null = null;

async function loadFromDisk(): Promise<StoreShape> {
  try {
    const raw = await fs.readFile(DATA_FILE, 'utf8');
    const parsed = JSON.parse(raw) as Partial<StoreShape>;
    if (!parsed.byUser || typeof parsed.byUser !== 'object') {
      return { byUser: {} };
    }
    return { byUser: parsed.byUser };
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      return { byUser: {} };
    }
    console.error('[memoryStore] load failed, starting empty:', err);
    return { byUser: {} };
  }
}

async function ensureLoaded(): Promise<StoreShape> {
  if (cache) return cache;
  if (!loadPromise) {
    loadPromise = loadFromDisk().then((s) => {
      cache = s;
      return s;
    });
  }
  return loadPromise;
}

async function persist(state: StoreShape): Promise<void> {
  await fs.mkdir(DATA_DIR, { recursive: true });
  const tmp = DATA_FILE + '.tmp';
  await fs.writeFile(tmp, JSON.stringify(state, null, 2), 'utf8');
  await fs.rename(tmp, DATA_FILE);
}

/** Pull the memory list for a single (user, scenario). Empty array when
 *  none exists. Returns the live ref — DO NOT mutate. */
export async function listMemories(userId: string, scenarioId: string): Promise<PlayMemory[]> {
  const s = await ensureLoaded();
  return s.byUser[userId]?.[scenarioId] ?? [];
}

/** Pull the per-scenario summary stats for a user — used by FiredLanding
 *  to show the "你打过 N 次" badge across the whole catalogue in one
 *  round-trip. Returns a map keyed by scenarioId. */
export interface ScenarioStats {
  playCount: number;
  bestRatio: number;
  lastOutcome: 'win' | 'partial' | 'lose';
  lastTactic: string;
}
export async function listScenarioStats(userId: string): Promise<Record<string, ScenarioStats>> {
  const s = await ensureLoaded();
  const userMap = s.byUser[userId];
  if (!userMap) return {};
  const out: Record<string, ScenarioStats> = {};
  for (const [scenarioId, memories] of Object.entries(userMap)) {
    if (!memories || memories.length === 0) continue;
    const last = memories[memories.length - 1];
    out[scenarioId] = {
      playCount:   memories.length,
      bestRatio:   memories.reduce((m, x) => Math.max(m, x.finalRatio), 0),
      lastOutcome: last.outcome,
      lastTactic:  last.tactic,
    };
  }
  return out;
}

/** Append a new memory and persist. Caps at MAX_MEMORIES_PER_SCENARIO,
 *  oldest dropped on overflow. */
export async function recordMemory(
  userId: string,
  scenarioId: string,
  memory: PlayMemory,
): Promise<void> {
  const s = await ensureLoaded();
  if (!s.byUser[userId]) s.byUser[userId] = {};
  if (!s.byUser[userId][scenarioId]) s.byUser[userId][scenarioId] = [];
  s.byUser[userId][scenarioId].push(memory);
  // Trim oldest first.
  if (s.byUser[userId][scenarioId].length > MAX_MEMORIES_PER_SCENARIO) {
    s.byUser[userId][scenarioId] = s.byUser[userId][scenarioId].slice(
      -MAX_MEMORIES_PER_SCENARIO,
    );
  }
  await persist(s);
}
