/**
 * v0.6.0 Room Furniture Catalog
 *
 * Each room has 3-6 pieces of furniture placed at fixed logical-world
 * coordinates inside the room rect (defined in `types/game.ts`).
 *
 * Why a static catalog and not procedurally placed:
 *   - Hand-tuned layout reads as "real office" instead of "random debris"
 *   - Stable positions let agents target specific items deterministically
 *     (Frank always sits at desk_dev_1 → his "work" caption can reference
 *     it consistently, future v0.6.1 lets us anchor the player avatar
 *     beside the furniture instead of the room centre)
 *   - Same data drives both the canvas render (sprite + label) and the
 *     activity-aware caption layer ("Frank 在 工位3 改 PPT")
 *
 * Design constraints used during placement:
 *   - Furniture must sit fully inside its room rect (no overlap with
 *     walls or doors). Use 16-24 px padding from room edges.
 *   - Same-type items in the same room get a `_1`/`_2` suffix so player
 *     captions can disambiguate ("工位 1" vs "工位 2").
 *   - Sizes are visual hints only — collision / pathfinding ignores them
 *     in v0.6.0 (planned for v0.6.2 with A* re-plan around furniture).
 */

import type { RoomRect } from '../types/game';
import { ROOM_RECTS } from '../types/game';

/** Catalog of furniture archetypes — keys mirror the iconGen sticker set
 *  generated by `regen-icons.ts furniture_*`. Adding a new archetype:
 *  (1) add a row here, (2) add `furniture_<key>` to `ICON_DETAILS`,
 *  (3) regen the sticker. The `cnLabel` is used in tooltips + speeches. */
export const FURNITURE_TYPES = {
  desk:            { cnLabel: '工位',     iconKey: 'furniture_desk',            w: 56, h: 40 },
  chair:           { cnLabel: '椅子',     iconKey: 'furniture_chair',           w: 24, h: 24 },
  meeting_table:   { cnLabel: '会议桌',   iconKey: 'furniture_meeting_table',   w: 84, h: 50 },
  whiteboard:      { cnLabel: '白板',     iconKey: 'furniture_whiteboard',      w: 60, h: 36 },
  coffee_machine:  { cnLabel: '咖啡机',   iconKey: 'furniture_coffee_machine',  w: 30, h: 36 },
  water_dispenser: { cnLabel: '饮水机',   iconKey: 'furniture_water_dispenser', w: 26, h: 36 },
  printer:         { cnLabel: '打印机',   iconKey: 'furniture_printer',         w: 38, h: 32 },
  server_rack:     { cnLabel: '服务器',   iconKey: 'furniture_server_rack',     w: 30, h: 50 },
  cctv:            { cnLabel: '监控屏',   iconKey: 'furniture_cctv',            w: 50, h: 38 },
  sofa:            { cnLabel: '沙发',     iconKey: 'furniture_sofa',            w: 70, h: 36 },
  plant:           { cnLabel: '绿植',     iconKey: 'furniture_plant',           w: 24, h: 30 },
  elevator_door:   { cnLabel: '电梯门',   iconKey: 'furniture_elevator',        w: 48, h: 48 },
} as const;

export type FurnitureKind = keyof typeof FURNITURE_TYPES;

/** A single placed instance. Coordinates are absolute in the same logical
 *  world space as `PlayerPosition` (0..MAP_W × 0..MAP_H). */
export interface FurnitureItem {
  /** Stable id, used in captions + future agent targeting. Convention:
   *  `<kind>_<roomShortId>_<n>` so "desk_dev_1" reads as "工位 1 in 产品部". */
  id: string;
  kind: FurnitureKind;
  roomId: string;
  x: number;
  y: number;
  /** Optional human label override. Defaults to "<cnLabel> N" computed
   *  from `kind`'s catalogue entry + the item's index in its room. */
  label?: string;
}

/** Compute a placement helper — returns N evenly-spaced points along a
 *  horizontal axis inside the given rect, with edge padding. */
function placeRow(rect: RoomRect, count: number, yOffset: number, padding = 28): Array<{ x: number; y: number }> {
  const inner = rect.w - padding * 2;
  const step = count > 1 ? inner / (count - 1) : 0;
  const out: Array<{ x: number; y: number }> = [];
  for (let i = 0; i < count; i++) {
    out.push({
      x: rect.x + padding + step * i,
      y: rect.y + yOffset,
    });
  }
  return out;
}

function room(id: string): RoomRect {
  const r = ROOM_RECTS.find((rr) => rr.id === id);
  if (!r) throw new Error(`Unknown room: ${id}`);
  return r;
}

// ---------------------------------------------------------------------------
// Per-room layout. Hand-placed for visual readability, not algorithmic.
// ---------------------------------------------------------------------------

const items: FurnitureItem[] = [];

// 茶水间 — pantry: coffee + water + sofa + plant
{
  const r = room('茶水间');
  items.push(
    { id: 'coffee_pantry', kind: 'coffee_machine',  roomId: r.id, x: r.x + 36,       y: r.y + 36 },
    { id: 'water_pantry',  kind: 'water_dispenser', roomId: r.id, x: r.x + 36,       y: r.y + 100 },
    { id: 'sofa_pantry',   kind: 'sofa',            roomId: r.id, x: r.x + r.w - 90, y: r.y + r.h - 60 },
    { id: 'plant_pantry',  kind: 'plant',           roomId: r.id, x: r.x + r.w - 40, y: r.y + 30 },
  );
}

// 电梯间 — elevator + plant
{
  const r = room('电梯间');
  items.push(
    { id: 'elevator_main', kind: 'elevator_door', roomId: r.id, x: r.x + r.w / 2 - 24, y: r.y + 30 },
    { id: 'plant_lift',    kind: 'plant',         roomId: r.id, x: r.x + 20,           y: r.y + r.h - 36 },
  );
}

// 会议室 — meeting table + whiteboard + 4 chairs
{
  const r = room('会议室');
  items.push(
    { id: 'mtable_main',  kind: 'meeting_table', roomId: r.id, x: r.x + r.w / 2 - 42, y: r.y + 70 },
    { id: 'whiteboard_1', kind: 'whiteboard',    roomId: r.id, x: r.x + r.w / 2 - 30, y: r.y + 20 },
  );
  // 4 chairs around the table
  const tableCx = r.x + r.w / 2;
  const tableCy = r.y + 95;
  items.push(
    { id: 'chair_meet_1', kind: 'chair', roomId: r.id, x: tableCx - 50, y: tableCy - 5 },
    { id: 'chair_meet_2', kind: 'chair', roomId: r.id, x: tableCx + 26, y: tableCy - 5 },
    { id: 'chair_meet_3', kind: 'chair', roomId: r.id, x: tableCx - 50, y: tableCy + 38 },
    { id: 'chair_meet_4', kind: 'chair', roomId: r.id, x: tableCx + 26, y: tableCy + 38 },
  );
}

// HR办公室 — 2 desks + 2 chairs + plant
{
  const r = room('HR办公室');
  const desks = placeRow(r, 2, 30, 36);
  desks.forEach((p, i) => {
    items.push({ id: `desk_hr_${i + 1}`,  kind: 'desk',  roomId: r.id, x: p.x - 28, y: p.y });
    items.push({ id: `chair_hr_${i + 1}`, kind: 'chair', roomId: r.id, x: p.x - 12, y: p.y + 50 });
  });
  items.push({ id: 'plant_hr', kind: 'plant', roomId: r.id, x: r.x + r.w - 30, y: r.y + r.h - 40 });
}

// 服务器机房 — 3 server racks (server-room density)
{
  const r = room('服务器机房');
  const racks = placeRow(r, 3, 60, 30);
  racks.forEach((p, i) => {
    items.push({ id: `server_rack_${i + 1}`, kind: 'server_rack', roomId: r.id, x: p.x - 15, y: p.y });
  });
}

// 开放工区 — 6 desks in 2 rows + water + plant
{
  const r = room('开放工区');
  const front = placeRow(r, 3, 60, 50);
  front.forEach((p, i) => {
    items.push({ id: `desk_dev_${i + 1}`,  kind: 'desk',  roomId: r.id, x: p.x - 28, y: p.y });
    items.push({ id: `chair_dev_${i + 1}`, kind: 'chair', roomId: r.id, x: p.x - 12, y: p.y + 50 });
  });
  const back = placeRow(r, 3, 140, 50);
  back.forEach((p, i) => {
    items.push({ id: `desk_dev_${i + 4}`,  kind: 'desk',  roomId: r.id, x: p.x - 28, y: p.y });
    items.push({ id: `chair_dev_${i + 4}`, kind: 'chair', roomId: r.id, x: p.x - 12, y: p.y + 50 });
  });
  items.push({ id: 'water_dev', kind: 'water_dispenser', roomId: r.id, x: r.x + r.w - 36, y: r.y + 24 });
  items.push({ id: 'plant_dev', kind: 'plant',           roomId: r.id, x: r.x + 18,       y: r.y + 24 });
}

// 监控室 — CCTV bank + chair
{
  const r = room('监控室');
  items.push(
    { id: 'cctv_main',   kind: 'cctv',  roomId: r.id, x: r.x + r.w / 2 - 25, y: r.y + 30 },
    { id: 'chair_cctv',  kind: 'chair', roomId: r.id, x: r.x + r.w / 2 - 12, y: r.y + 90 },
  );
}

// 产品部 — 4 desks + plant
{
  const r = room('产品部');
  const desks = placeRow(r, 2, 50, 36);
  desks.forEach((p, i) => {
    items.push({ id: `desk_pm_${i + 1}`,  kind: 'desk',  roomId: r.id, x: p.x - 28, y: p.y });
    items.push({ id: `chair_pm_${i + 1}`, kind: 'chair', roomId: r.id, x: p.x - 12, y: p.y + 50 });
  });
  const desks2 = placeRow(r, 2, 130, 36);
  desks2.forEach((p, i) => {
    items.push({ id: `desk_pm_${i + 3}`,  kind: 'desk',  roomId: r.id, x: p.x - 28, y: p.y });
    items.push({ id: `chair_pm_${i + 3}`, kind: 'chair', roomId: r.id, x: p.x - 12, y: p.y + 50 });
  });
  items.push({ id: 'plant_pm', kind: 'plant', roomId: r.id, x: r.x + r.w - 30, y: r.y + r.h - 40 });
}

// 老板办公室 — meeting table + sofa + whiteboard + plant
{
  const r = room('老板办公室');
  items.push(
    { id: 'mtable_boss',     kind: 'meeting_table', roomId: r.id, x: r.x + 60,       y: r.y + 60 },
    { id: 'sofa_boss',       kind: 'sofa',          roomId: r.id, x: r.x + r.w - 90, y: r.y + r.h - 60 },
    { id: 'whiteboard_boss', kind: 'whiteboard',    roomId: r.id, x: r.x + r.w - 80, y: r.y + 20 },
    { id: 'plant_boss',      kind: 'plant',         roomId: r.id, x: r.x + 20,       y: r.y + r.h - 40 },
  );
}

// 文印室 — 2 printers + chair
{
  const r = room('文印室');
  const printers = placeRow(r, 2, 60, 36);
  printers.forEach((p, i) => {
    items.push({ id: `printer_${i + 1}`, kind: 'printer', roomId: r.id, x: p.x - 19, y: p.y });
  });
  items.push({ id: 'chair_print', kind: 'chair', roomId: r.id, x: r.x + r.w / 2 - 12, y: r.y + r.h - 50 });
}

export const ROOM_FURNITURE: FurnitureItem[] = items;

// ---------------------------------------------------------------------------
// Lookup helpers — both sides import these. Pure, side-effect-free.
// ---------------------------------------------------------------------------

export function furnitureInRoom(roomId: string): FurnitureItem[] {
  return ROOM_FURNITURE.filter((f) => f.roomId === roomId);
}

/** Return the closest furniture item to a player position within `maxDist`
 *  logical pixels, or null if none qualify. Used by the server to upgrade
 *  generic "work" activities into "work@desk_dev_3" style captions, and by
 *  the client to highlight the focused item with a soft ring. */
export function nearestFurniture(
  roomId: string,
  px: number,
  py: number,
  maxDist = 60,
): FurnitureItem | null {
  let best: FurnitureItem | null = null;
  let bestSq = maxDist * maxDist;
  for (const f of ROOM_FURNITURE) {
    if (f.roomId !== roomId) continue;
    const def = FURNITURE_TYPES[f.kind];
    const cx = f.x + def.w / 2;
    const cy = f.y + def.h / 2;
    const dx = cx - px;
    const dy = cy - py;
    const d = dx * dx + dy * dy;
    if (d < bestSq) {
      bestSq = d;
      best = f;
    }
  }
  return best;
}

/** Render-friendly label for an item — "工位 3" etc. Server uses this to
 *  generate activity captions, client uses it for hover tooltips. */
export function labelFor(item: FurnitureItem): string {
  if (item.label) return item.label;
  const def = FURNITURE_TYPES[item.kind];
  // Number same-kind items within a room: "工位 1", "工位 2"...
  const sameKindInRoom = ROOM_FURNITURE
    .filter((f) => f.roomId === item.roomId && f.kind === item.kind);
  if (sameKindInRoom.length <= 1) return def.cnLabel;
  const idx = sameKindInRoom.findIndex((f) => f.id === item.id);
  return `${def.cnLabel} ${idx + 1}`;
}
