/**
 * squad — v1.4.1 "你们这一桌的故事" types.
 *
 * 2-4 friends form a squad; each has a quiz archetype. Once the host
 * starts, the LLM director generates a 5-act workplace sitcom that
 * names each player by their archetype + role and uses their
 * personalities to drive scenes. Everyone reads the story together —
 * one act at a time, host controls "下一幕" — then a recap card at
 * the end is screenshot-friendly for sharing.
 *
 * Why no live audio / no real-time turn-based play: keeps the v1.4.1
 * MVP shippable in one cut. v1.4.2 can add per-line voice TTS using
 * each player's archetype voice (q.v. ARCHETYPE_TO_TALKSHOW_PERSONA).
 */

export interface SquadMember {
  /** Pseudonymous X-User-Id. Stable identity across sessions. */
  userId: string;
  /** Display name — defaults to "员工 N" if user hasn't set anything. */
  displayName: string;
  /** Archetype id from the quiz, if user has taken it. Anonymous
   *  members get a default "neutral office body" archetype on the
   *  director side. */
  archetypeId?: string;
  archetypeName?: string;
  archetypeEmoji?: string;
  /** Whether this member is the squad host (got first dibs on /create). */
  isHost: boolean;
  /** Wall-clock when they joined the room (for stable seat ordering). */
  joinedAt: number;
}

export interface SquadActBeat {
  /** Speaker's userId; "narrator" for the omniscient narrator who
   *  introduces each scene. */
  speakerUserId: string | 'narrator';
  /** Speaker's display name + emoji at the time of generation —
   *  cached in the beat so re-rendering after a member disconnects
   *  still reads cleanly. */
  speakerLabel: string;
  /** The actual line. */
  line: string;
}

export interface SquadAct {
  /** 1..N (1-indexed for human readability). */
  index: number;
  /** One-line scene title — "第一幕:周一早会的预言" type. */
  title: string;
  /** 4-7 beats per act mixing narration and member dialogue. */
  beats: SquadActBeat[];
  /** Optional callout that names ONE member to "speak next IRL" —
   *  group chat prompt fuel. Null when the act self-contains. */
  realLifePrompt?: {
    targetUserId: string;
    prompt: string;
  };
}

export interface SquadRecap {
  /** 1-line headline summarizing the whole story. */
  headline: string;
  /** Per-member 1-line "MVP / 戏精 / 隐形人" awards. */
  awards: Array<{ userId: string; label: string; line: string }>;
  /** Bottom-line closer for the shareable card. */
  closer: string;
}

export interface SquadRoom {
  id: string;
  /** Lifecycle:
   *    'lobby'   — accepting members, host hasn't pressed start
   *    'directing' — host pressed start, LLM is generating (~5-10s)
   *    'playing' — generated, host can advance acts
   *    'ended'   — recap displayed, room kept for 30 min then GC'd */
  status: 'lobby' | 'directing' | 'playing' | 'ended';
  members: SquadMember[];
  /** 2-4. Host sets at create time (default 4). */
  maxMembers: number;
  /** Host-provided freeform context ("我们在一家做 AI 的小厂"). LLM
   *  uses this to color the story. Optional. */
  scenarioBrief?: string;
  /** Generated by squadDirector on `start`. Empty until then. */
  acts: SquadAct[];
  /** 0-based index of the currently-revealed act (clients clamp to
   *  acts.length when status === 'ended'). */
  currentActIndex: number;
  /** Generated by squadDirector alongside acts. Surfaced when
   *  status === 'ended'. */
  recap?: SquadRecap;
  /** Wall-clock for TTL sweeper. */
  createdAt: number;
}

/** v1.4.1 — default # of acts when the director runs. Keep at 5 for
 *  the MVP since that's a comfortable "watch through in ~5 min" beat,
 *  matches the pack length convention, and fits within a single LLM
 *  call without breaking max-tokens. */
export const SQUAD_ACT_COUNT = 5;

/** Director's system prompt — kept here in shared so client and server
 *  can both reference it (client may show a "正在编剧:..." spoiler on
 *  the directing screen). */
export const SQUAD_DIRECTOR_SYSTEM_PROMPT = `你是一个中文职场情景剧导演。
任务:给你一个 2-4 人小队的"班味档案"(每人的 archetype + emoji + 性格 +
可能的 region/industry 标签),你要写一出 5 幕的职场连续剧,每幕展示一个真实
办公室小场景。

风格要求:
- 每幕都有 4-7 个 beat,beat 是一行台词或旁白
- 每幕开头是一句旁白(narrator)铺垫场景
- 每个角色的台词要扣紧他的 archetype 性格(卷王=拼命喊"冲"、阴阳怪气王=干瘪的"挺好的"、显眼包=戏剧化反应)
- 全部角色都至少出场 2 次,不能让某个 squad 成员没戏
- 5 幕之间要有连贯的情节弧:周一早会 → 中午茶水间 → 下午临时加班通知 → 晚上群消息互怼 → 周五"复盘会"反转
- 每幕末尾可选一个 realLifePrompt:点一个具体的 squad 成员,让他在群里 / 现实中回一句话(比如"@张三,这个怎么解释?")

v3.0.0 — chemistry-aware 编剧准则(重要):
- 用户输入会包含一个"小队化学反应分析"块。这是预计算的群体动力学提示,
  你 必 须 把这些动力学融入 5 幕的情节弧中,不能写一个"任何小队都可以"
  的通用故事。
- 如果有"行业碰撞"或"地域碰撞"分析,前两幕就要让冲突外显(例如国企+
  大厂同台,第一幕的早会就让国企同事掏纸质笔记本而大厂同事打开 OKR
  系统,二者眼神尴尬交汇)。
- 如果有"同城群像"或"同行业群像"分析,要密集使用该群体的内部黑话 /
  共同痛点(北漂群像 → 提五号线 / 沙县;杭州互联网群像 → 提花名 / 中台)。
- 如果有"天敌同台"分析,从第一幕就要让两人有眼神戏 / 微妙摩擦,第三
  四幕爆发,最后一幕和解或彻底翻脸。
- 如果有"trait 两极"分析,做对照镜头(卷王深夜加班 vs 摆烂派准点下班
  的剪影对比)。

内容安全:
- 严禁出现真人姓名(squad 成员之外的)/真公司名/政治内容
- 不要写裁员 / 自杀 / 暴力等沉重情节

输出格式: STRICT JSON,不要 markdown 围栏不要任何前缀,严格按这个 schema:
{
  "acts": [
    {
      "index": 1,
      "title": "第一幕:周一早会的预言",
      "beats": [
        {"speakerUserId":"narrator","speakerLabel":"旁白","line":"..."},
        {"speakerUserId":"u-xxx","speakerLabel":"🔥 卷王 · 张三","line":"..."}
      ],
      "realLifePrompt": {"targetUserId":"u-yyy","prompt":"@xxx 你这次怎么甩锅?"}
    },
    ... 5 acts total ...
  ],
  "recap": {
    "headline": "...",
    "awards": [
      {"userId":"u-xxx","label":"💎 MVP","line":"全场最佳:..."},
      ...
    ],
    "closer": "..."
  }
}`;
